// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: mcp/v1/mcp_tool_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPToolService_ListTools_FullMethodName      = "/portcullis.mcp.v1.MCPToolService/ListTools"
	MCPToolService_CallTool_FullMethodName       = "/portcullis.mcp.v1.MCPToolService/CallTool"
	MCPToolService_CallToolStream_FullMethodName = "/portcullis.mcp.v1.MCPToolService/CallToolStream"
)

// MCPToolServiceClient is the client API for MCPToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPToolService exposes MCP tool discovery and invocation over gRPC.
//
// Clients use ListTools to discover available tools and their schemas, CallTool
// for synchronous invocations, and CallToolStream for invocations that deliver
// progress events before the final result.
type MCPToolServiceClient interface {
	// ListTools returns all tools currently registered in the gateway along with
	// their schemas.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// CallTool performs a synchronous tool invocation and returns the result.
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
	// CallToolStream performs a tool invocation with streaming progress support.
	// The server sends zero or more CallToolStreamResponse messages containing
	// ProgressEvent payloads, followed by exactly one message containing the
	// final CallToolResponse.
	CallToolStream(ctx context.Context, in *CallToolStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallToolStreamResponse], error)
}

type mCPToolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPToolServiceClient(cc grpc.ClientConnInterface) MCPToolServiceClient {
	return &mCPToolServiceClient{cc}
}

func (c *mCPToolServiceClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, MCPToolService_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPToolServiceClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, MCPToolService_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPToolServiceClient) CallToolStream(ctx context.Context, in *CallToolStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CallToolStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MCPToolService_ServiceDesc.Streams[0], MCPToolService_CallToolStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallToolStreamRequest, CallToolStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCPToolService_CallToolStreamClient = grpc.ServerStreamingClient[CallToolStreamResponse]

// MCPToolServiceServer is the server API for MCPToolService service.
// All implementations must embed UnimplementedMCPToolServiceServer
// for forward compatibility.
//
// MCPToolService exposes MCP tool discovery and invocation over gRPC.
//
// Clients use ListTools to discover available tools and their schemas, CallTool
// for synchronous invocations, and CallToolStream for invocations that deliver
// progress events before the final result.
type MCPToolServiceServer interface {
	// ListTools returns all tools currently registered in the gateway along with
	// their schemas.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// CallTool performs a synchronous tool invocation and returns the result.
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	// CallToolStream performs a tool invocation with streaming progress support.
	// The server sends zero or more CallToolStreamResponse messages containing
	// ProgressEvent payloads, followed by exactly one message containing the
	// final CallToolResponse.
	CallToolStream(*CallToolStreamRequest, grpc.ServerStreamingServer[CallToolStreamResponse]) error
	mustEmbedUnimplementedMCPToolServiceServer()
}

// UnimplementedMCPToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPToolServiceServer struct{}

func (UnimplementedMCPToolServiceServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedMCPToolServiceServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMCPToolServiceServer) CallToolStream(*CallToolStreamRequest, grpc.ServerStreamingServer[CallToolStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method CallToolStream not implemented")
}
func (UnimplementedMCPToolServiceServer) mustEmbedUnimplementedMCPToolServiceServer() {}
func (UnimplementedMCPToolServiceServer) testEmbeddedByValue()                        {}

// UnsafeMCPToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPToolServiceServer will
// result in compilation errors.
type UnsafeMCPToolServiceServer interface {
	mustEmbedUnimplementedMCPToolServiceServer()
}

func RegisterMCPToolServiceServer(s grpc.ServiceRegistrar, srv MCPToolServiceServer) {
	// If the following call panics, it indicates UnimplementedMCPToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPToolService_ServiceDesc, srv)
}

func _MCPToolService_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPToolServiceServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPToolService_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPToolServiceServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPToolService_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPToolServiceServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPToolService_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPToolServiceServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPToolService_CallToolStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallToolStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MCPToolServiceServer).CallToolStream(m, &grpc.GenericServerStream[CallToolStreamRequest, CallToolStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCPToolService_CallToolStreamServer = grpc.ServerStreamingServer[CallToolStreamResponse]

// MCPToolService_ServiceDesc is the grpc.ServiceDesc for MCPToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portcullis.mcp.v1.MCPToolService",
	HandlerType: (*MCPToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTools",
			Handler:    _MCPToolService_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _MCPToolService_CallTool_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallToolStream",
			Handler:       _MCPToolService_CallToolStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcp/v1/mcp_tool_service.proto",
}
