// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mcp/v1/mcp_tool_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListToolsRequest is the input for the ListTools RPC.
// Currently empty; reserved for future filtering parameters.
type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{0}
}

// ListToolsResponse contains all tools registered in the gateway.
type ListToolsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tools is the set of registered tools with their schemas.
	Tools         []*ToolInfo `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolInfo describes a single registered tool and its capabilities.
type ToolInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique gateway tool identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// schemas lists the individual tool capabilities exposed by this tool.
	// A tool with no schemas exposes a single pass-through capability.
	Schemas       []*ToolSchema `protobuf:"bytes,2,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{2}
}

func (x *ToolInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolInfo) GetSchemas() []*ToolSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

// ToolSchema describes a single MCP tool capability as reported by the
// backend MCP server.
type ToolSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the MCP tool name as reported by the backend server.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description is the human-readable description of the tool.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// input_schema is the JSON Schema describing the tool's input parameters,
	// encoded as JSON bytes. Using bytes rather than typed proto fields allows
	// transport-agnostic forwarding of arbitrary schemas.
	InputSchema   []byte `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSchema) Reset() {
	*x = ToolSchema{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSchema) ProtoMessage() {}

func (x *ToolSchema) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSchema.ProtoReflect.Descriptor instead.
func (*ToolSchema) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{3}
}

func (x *ToolSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSchema) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

// CallToolRequest is the input for the CallTool RPC.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tool_name is the name of the tool to invoke. This must match either a
	// tool ID (for single-capability tools) or a schema name (for
	// multi-capability tools).
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// arguments is the JSON-encoded invocation arguments. Using bytes rather
	// than typed proto fields allows transport-agnostic forwarding of arbitrary
	// tool parameters.
	Arguments     []byte `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{4}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CallToolResponse is the result of a tool invocation.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// content contains the tool's output as a list of content items.
	Content []*ContentItem `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	// is_error indicates whether the tool reported an error condition.
	IsError bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// structured_content is the full output map serialized as JSON bytes.
	// Present when the tool produces structured output that cannot be fully
	// represented by the content items alone.
	StructuredContent []byte `protobuf:"bytes,3,opt,name=structured_content,json=structuredContent,proto3" json:"structured_content,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{5}
}

func (x *CallToolResponse) GetContent() []*ContentItem {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *CallToolResponse) GetStructuredContent() []byte {
	if x != nil {
		return x.StructuredContent
	}
	return nil
}

// ContentItem represents a single piece of content in a tool response.
type ContentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type identifies the content kind (e.g. "text", "image", "audio").
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// text holds the textual content when type is "text".
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// data holds base64-encoded binary content for non-text types.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// mime_type is the MIME type of the content when applicable.
	MimeType      string `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentItem) Reset() {
	*x = ContentItem{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentItem) ProtoMessage() {}

func (x *ContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentItem.ProtoReflect.Descriptor instead.
func (*ContentItem) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{6}
}

func (x *ContentItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContentItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContentItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ContentItem) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// CallToolStreamRequest is the input for the CallToolStream RPC.
type CallToolStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tool_name is the name of the tool to invoke.
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// arguments is the JSON-encoded invocation arguments.
	Arguments     []byte `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolStreamRequest) Reset() {
	*x = CallToolStreamRequest{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolStreamRequest) ProtoMessage() {}

func (x *CallToolStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolStreamRequest.ProtoReflect.Descriptor instead.
func (*CallToolStreamRequest) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{7}
}

func (x *CallToolStreamRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolStreamRequest) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CallToolStreamResponse is a single message in the CallToolStream response
// stream. Each message contains either a progress event or the final result.
type CallToolStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CallToolStreamResponse_Progress
	//	*CallToolStreamResponse_Result
	Payload       isCallToolStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolStreamResponse) Reset() {
	*x = CallToolStreamResponse{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolStreamResponse) ProtoMessage() {}

func (x *CallToolStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolStreamResponse.ProtoReflect.Descriptor instead.
func (*CallToolStreamResponse) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{8}
}

func (x *CallToolStreamResponse) GetPayload() isCallToolStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallToolStreamResponse) GetProgress() *ProgressEvent {
	if x != nil {
		if x, ok := x.Payload.(*CallToolStreamResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *CallToolStreamResponse) GetResult() *CallToolResponse {
	if x != nil {
		if x, ok := x.Payload.(*CallToolStreamResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isCallToolStreamResponse_Payload interface {
	isCallToolStreamResponse_Payload()
}

type CallToolStreamResponse_Progress struct {
	// progress is an intermediate progress notification.
	Progress *ProgressEvent `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type CallToolStreamResponse_Result struct {
	// result is the final tool invocation result. Exactly one result message
	// is sent as the last message in the stream.
	Result *CallToolResponse `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*CallToolStreamResponse_Progress) isCallToolStreamResponse_Payload() {}

func (*CallToolStreamResponse_Result) isCallToolStreamResponse_Payload() {}

// ProgressEvent represents an intermediate progress notification during a
// streaming tool invocation. Fields mirror the MCP notifications/progress
// schema.
type ProgressEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// progress_token is the opaque token correlating this notification with
	// the originating request.
	ProgressToken string `protobuf:"bytes,1,opt,name=progress_token,json=progressToken,proto3" json:"progress_token,omitempty"`
	// progress is the current progress value (e.g. bytes transferred).
	Progress float64 `protobuf:"fixed64,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// total is the expected total value. Zero means total is unknown.
	Total float64 `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	// message is an optional human-readable description of the current step.
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_v1_mcp_tool_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_mcp_v1_mcp_tool_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProgressEvent) GetProgressToken() string {
	if x != nil {
		return x.ProgressToken
	}
	return ""
}

func (x *ProgressEvent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressEvent) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mcp_v1_mcp_tool_service_proto protoreflect.FileDescriptor

const file_mcp_v1_mcp_tool_service_proto_rawDesc = "" +
	"\n" +
	"\x1dmcp/v1/mcp_tool_service.proto\x12\x11portcullis.mcp.v1\"\x12\n" +
	"\x10ListToolsRequest\"F\n" +
	"\x11ListToolsResponse\x121\n" +
	"\x05tools\x18\x01 \x03(\v2\x1b.portcullis.mcp.v1.ToolInfoR\x05tools\"S\n" +
	"\bToolInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\aschemas\x18\x02 \x03(\v2\x1d.portcullis.mcp.v1.ToolSchemaR\aschemas\"e\n" +
	"\n" +
	"ToolSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\fR\vinputSchema\"L\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\fR\targuments\"\x96\x01\n" +
	"\x10CallToolResponse\x128\n" +
	"\acontent\x18\x01 \x03(\v2\x1e.portcullis.mcp.v1.ContentItemR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\x12-\n" +
	"\x12structured_content\x18\x03 \x01(\fR\x11structuredContent\"f\n" +
	"\vContentItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\"R\n" +
	"\x15CallToolStreamRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\fR\targuments\"\xa2\x01\n" +
	"\x16CallToolStreamResponse\x12>\n" +
	"\bprogress\x18\x01 \x01(\v2 .portcullis.mcp.v1.ProgressEventH\x00R\bprogress\x12=\n" +
	"\x06result\x18\x02 \x01(\v2#.portcullis.mcp.v1.CallToolResponseH\x00R\x06resultB\t\n" +
	"\apayload\"\x82\x01\n" +
	"\rProgressEvent\x12%\n" +
	"\x0eprogress_token\x18\x01 \x01(\tR\rprogressToken\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x01R\bprogress\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xa6\x02\n" +
	"\x0eMCPToolService\x12V\n" +
	"\tListTools\x12#.portcullis.mcp.v1.ListToolsRequest\x1a$.portcullis.mcp.v1.ListToolsResponse\x12S\n" +
	"\bCallTool\x12\".portcullis.mcp.v1.CallToolRequest\x1a#.portcullis.mcp.v1.CallToolResponse\x12g\n" +
	"\x0eCallToolStream\x12(.portcullis.mcp.v1.CallToolStreamRequest\x1a).portcullis.mcp.v1.CallToolStreamResponse0\x01B\xcd\x01\n" +
	"\x15com.portcullis.mcp.v1B\x13McpToolServiceProtoH\x02P\x01Z7github.com/tochemey/portcullis/internal/ingress/grpc/pb\xa2\x02\x03PMX\xaa\x02\x11Portcullis.Mcp.V1\xca\x02\x11Portcullis\\Mcp\\V1\xe2\x02\x1dPortcullis\\Mcp\\V1\\GPBMetadata\xea\x02\x13Portcullis::Mcp::V1b\x06proto3"

var (
	file_mcp_v1_mcp_tool_service_proto_rawDescOnce sync.Once
	file_mcp_v1_mcp_tool_service_proto_rawDescData []byte
)

func file_mcp_v1_mcp_tool_service_proto_rawDescGZIP() []byte {
	file_mcp_v1_mcp_tool_service_proto_rawDescOnce.Do(func() {
		file_mcp_v1_mcp_tool_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_v1_mcp_tool_service_proto_rawDesc), len(file_mcp_v1_mcp_tool_service_proto_rawDesc)))
	})
	return file_mcp_v1_mcp_tool_service_proto_rawDescData
}

var file_mcp_v1_mcp_tool_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mcp_v1_mcp_tool_service_proto_goTypes = []any{
	(*ListToolsRequest)(nil),       // 0: portcullis.mcp.v1.ListToolsRequest
	(*ListToolsResponse)(nil),      // 1: portcullis.mcp.v1.ListToolsResponse
	(*ToolInfo)(nil),               // 2: portcullis.mcp.v1.ToolInfo
	(*ToolSchema)(nil),             // 3: portcullis.mcp.v1.ToolSchema
	(*CallToolRequest)(nil),        // 4: portcullis.mcp.v1.CallToolRequest
	(*CallToolResponse)(nil),       // 5: portcullis.mcp.v1.CallToolResponse
	(*ContentItem)(nil),            // 6: portcullis.mcp.v1.ContentItem
	(*CallToolStreamRequest)(nil),  // 7: portcullis.mcp.v1.CallToolStreamRequest
	(*CallToolStreamResponse)(nil), // 8: portcullis.mcp.v1.CallToolStreamResponse
	(*ProgressEvent)(nil),          // 9: portcullis.mcp.v1.ProgressEvent
}
var file_mcp_v1_mcp_tool_service_proto_depIdxs = []int32{
	2, // 0: portcullis.mcp.v1.ListToolsResponse.tools:type_name -> portcullis.mcp.v1.ToolInfo
	3, // 1: portcullis.mcp.v1.ToolInfo.schemas:type_name -> portcullis.mcp.v1.ToolSchema
	6, // 2: portcullis.mcp.v1.CallToolResponse.content:type_name -> portcullis.mcp.v1.ContentItem
	9, // 3: portcullis.mcp.v1.CallToolStreamResponse.progress:type_name -> portcullis.mcp.v1.ProgressEvent
	5, // 4: portcullis.mcp.v1.CallToolStreamResponse.result:type_name -> portcullis.mcp.v1.CallToolResponse
	0, // 5: portcullis.mcp.v1.MCPToolService.ListTools:input_type -> portcullis.mcp.v1.ListToolsRequest
	4, // 6: portcullis.mcp.v1.MCPToolService.CallTool:input_type -> portcullis.mcp.v1.CallToolRequest
	7, // 7: portcullis.mcp.v1.MCPToolService.CallToolStream:input_type -> portcullis.mcp.v1.CallToolStreamRequest
	1, // 8: portcullis.mcp.v1.MCPToolService.ListTools:output_type -> portcullis.mcp.v1.ListToolsResponse
	5, // 9: portcullis.mcp.v1.MCPToolService.CallTool:output_type -> portcullis.mcp.v1.CallToolResponse
	8, // 10: portcullis.mcp.v1.MCPToolService.CallToolStream:output_type -> portcullis.mcp.v1.CallToolStreamResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_mcp_v1_mcp_tool_service_proto_init() }
func file_mcp_v1_mcp_tool_service_proto_init() {
	if File_mcp_v1_mcp_tool_service_proto != nil {
		return
	}
	file_mcp_v1_mcp_tool_service_proto_msgTypes[8].OneofWrappers = []any{
		(*CallToolStreamResponse_Progress)(nil),
		(*CallToolStreamResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_v1_mcp_tool_service_proto_rawDesc), len(file_mcp_v1_mcp_tool_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_v1_mcp_tool_service_proto_goTypes,
		DependencyIndexes: file_mcp_v1_mcp_tool_service_proto_depIdxs,
		MessageInfos:      file_mcp_v1_mcp_tool_service_proto_msgTypes,
	}.Build()
	File_mcp_v1_mcp_tool_service_proto = out.File
	file_mcp_v1_mcp_tool_service_proto_goTypes = nil
	file_mcp_v1_mcp_tool_service_proto_depIdxs = nil
}
