// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: egrpc/test_service.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is an enum used by RichRequest.
type Status int32

const (
	Status_STATUS_NONE     Status = 0
	Status_STATUS_ACTIVE   Status = 1
	Status_STATUS_INACTIVE Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_NONE",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_NONE":     0,
		"STATUS_ACTIVE":   1,
		"STATUS_INACTIVE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_egrpc_test_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_egrpc_test_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{0}
}

// EchoRequest is the input for the Echo and StreamEcho RPCs.
type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_egrpc_test_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// EchoResponse is the output for the Echo and StreamEcho RPCs.
type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_egrpc_test_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// RichRequest exercises various protobuf field types.
type RichRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	BigNumber     int64                  `protobuf:"varint,3,opt,name=big_number,json=bigNumber,proto3" json:"big_number,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Ratio         float32                `protobuf:"fixed32,6,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Address       *Address               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Status        Status                 `protobuf:"varint,11,opt,name=status,proto3,enum=testpkg.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichRequest) Reset() {
	*x = RichRequest{}
	mi := &file_egrpc_test_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichRequest) ProtoMessage() {}

func (x *RichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichRequest.ProtoReflect.Descriptor instead.
func (*RichRequest) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{2}
}

func (x *RichRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RichRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RichRequest) GetBigNumber() int64 {
	if x != nil {
		return x.BigNumber
	}
	return 0
}

func (x *RichRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *RichRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RichRequest) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *RichRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RichRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RichRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RichRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RichRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_NONE
}

// Address is a nested message used by RichRequest.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Zip           int32                  `protobuf:"varint,3,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_egrpc_test_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZip() int32 {
	if x != nil {
		return x.Zip
	}
	return 0
}

// RichResponse is the response for RichService.Process.
type RichResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RichResponse) Reset() {
	*x = RichResponse{}
	mi := &file_egrpc_test_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichResponse) ProtoMessage() {}

func (x *RichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichResponse.ProtoReflect.Descriptor instead.
func (*RichResponse) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{4}
}

func (x *RichResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// TreeNode is a self-referencing message for testing cycle detection in schema
// generation.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Left          *TreeNode              `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right         *TreeNode              `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_egrpc_test_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_test_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_egrpc_test_service_proto_rawDescGZIP(), []int{5}
}

func (x *TreeNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TreeNode) GetLeft() *TreeNode {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *TreeNode) GetRight() *TreeNode {
	if x != nil {
		return x.Right
	}
	return nil
}

var File_egrpc_test_service_proto protoreflect.FileDescriptor

const file_egrpc_test_service_proto_rawDesc = "" +
	"\n" +
	"\x18egrpc/test_service.proto\x12\atestpkg\"=\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"D\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\"\x8e\x03\n" +
	"\vRichRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"big_number\x18\x03 \x01(\x03R\tbigNumber\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x14\n" +
	"\x05ratio\x18\x06 \x01(\x02R\x05ratio\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x128\n" +
	"\x06labels\x18\t \x03(\v2 .testpkg.RichRequest.LabelsEntryR\x06labels\x12*\n" +
	"\aaddress\x18\n" +
	" \x01(\v2\x10.testpkg.AddressR\aaddress\x12'\n" +
	"\x06status\x18\v \x01(\x0e2\x0f.testpkg.StatusR\x06status\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x03 \x01(\x05R\x03zip\"&\n" +
	"\fRichResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"p\n" +
	"\bTreeNode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12%\n" +
	"\x04left\x18\x02 \x01(\v2\x11.testpkg.TreeNodeR\x04left\x12'\n" +
	"\x05right\x18\x03 \x01(\v2\x11.testpkg.TreeNodeR\x05right*A\n" +
	"\x06Status\x12\x0f\n" +
	"\vSTATUS_NONE\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x022\x7f\n" +
	"\vTestService\x123\n" +
	"\x04Echo\x12\x14.testpkg.EchoRequest\x1a\x15.testpkg.EchoResponse\x12;\n" +
	"\n" +
	"StreamEcho\x12\x14.testpkg.EchoRequest\x1a\x15.testpkg.EchoResponse0\x012E\n" +
	"\vRichService\x126\n" +
	"\aProcess\x12\x14.testpkg.RichRequest\x1a\x15.testpkg.RichResponse2B\n" +
	"\x0eSelfRefService\x120\n" +
	"\bTraverse\x12\x11.testpkg.TreeNode\x1a\x11.testpkg.TreeNodeB\x97\x01\n" +
	"\vcom.testpkgB\x10TestServiceProtoH\x02P\x01Z8github.com/tochemey/mcgate/internal/egress/grpc/testdata\xa2\x02\x03TXX\xaa\x02\aTestpkg\xca\x02\aTestpkg\xe2\x02\x13Testpkg\\GPBMetadata\xea\x02\aTestpkgb\x06proto3"

var (
	file_egrpc_test_service_proto_rawDescOnce sync.Once
	file_egrpc_test_service_proto_rawDescData []byte
)

func file_egrpc_test_service_proto_rawDescGZIP() []byte {
	file_egrpc_test_service_proto_rawDescOnce.Do(func() {
		file_egrpc_test_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_egrpc_test_service_proto_rawDesc), len(file_egrpc_test_service_proto_rawDesc)))
	})
	return file_egrpc_test_service_proto_rawDescData
}

var file_egrpc_test_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_egrpc_test_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_egrpc_test_service_proto_goTypes = []any{
	(Status)(0),          // 0: testpkg.Status
	(*EchoRequest)(nil),  // 1: testpkg.EchoRequest
	(*EchoResponse)(nil), // 2: testpkg.EchoResponse
	(*RichRequest)(nil),  // 3: testpkg.RichRequest
	(*Address)(nil),      // 4: testpkg.Address
	(*RichResponse)(nil), // 5: testpkg.RichResponse
	(*TreeNode)(nil),     // 6: testpkg.TreeNode
	nil,                  // 7: testpkg.RichRequest.LabelsEntry
}
var file_egrpc_test_service_proto_depIdxs = []int32{
	7, // 0: testpkg.RichRequest.labels:type_name -> testpkg.RichRequest.LabelsEntry
	4, // 1: testpkg.RichRequest.address:type_name -> testpkg.Address
	0, // 2: testpkg.RichRequest.status:type_name -> testpkg.Status
	6, // 3: testpkg.TreeNode.left:type_name -> testpkg.TreeNode
	6, // 4: testpkg.TreeNode.right:type_name -> testpkg.TreeNode
	1, // 5: testpkg.TestService.Echo:input_type -> testpkg.EchoRequest
	1, // 6: testpkg.TestService.StreamEcho:input_type -> testpkg.EchoRequest
	3, // 7: testpkg.RichService.Process:input_type -> testpkg.RichRequest
	6, // 8: testpkg.SelfRefService.Traverse:input_type -> testpkg.TreeNode
	2, // 9: testpkg.TestService.Echo:output_type -> testpkg.EchoResponse
	2, // 10: testpkg.TestService.StreamEcho:output_type -> testpkg.EchoResponse
	5, // 11: testpkg.RichService.Process:output_type -> testpkg.RichResponse
	6, // 12: testpkg.SelfRefService.Traverse:output_type -> testpkg.TreeNode
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_egrpc_test_service_proto_init() }
func file_egrpc_test_service_proto_init() {
	if File_egrpc_test_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_egrpc_test_service_proto_rawDesc), len(file_egrpc_test_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_egrpc_test_service_proto_goTypes,
		DependencyIndexes: file_egrpc_test_service_proto_depIdxs,
		EnumInfos:         file_egrpc_test_service_proto_enumTypes,
		MessageInfos:      file_egrpc_test_service_proto_msgTypes,
	}.Build()
	File_egrpc_test_service_proto = out.File
	file_egrpc_test_service_proto_goTypes = nil
	file_egrpc_test_service_proto_depIdxs = nil
}
