// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: egrpc/test_service.proto

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_Echo_FullMethodName       = "/testpkg.TestService/Echo"
	TestService_StreamEcho_FullMethodName = "/testpkg.TestService/StreamEcho"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestService is a simple gRPC service used for unit testing the gRPC egress
// transport layer.
type TestServiceClient interface {
	// Echo returns the input message unchanged.
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// StreamEcho returns the input message multiple times as a server stream.
	StreamEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, TestService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) StreamEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_StreamEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_StreamEchoClient = grpc.ServerStreamingClient[EchoResponse]

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
//
// TestService is a simple gRPC service used for unit testing the gRPC egress
// transport layer.
type TestServiceServer interface {
	// Echo returns the input message unchanged.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// StreamEcho returns the input message multiple times as a server stream.
	StreamEcho(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedTestServiceServer) StreamEcho(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEcho not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_StreamEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).StreamEcho(m, &grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_StreamEchoServer = grpc.ServerStreamingServer[EchoResponse]

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testpkg.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TestService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEcho",
			Handler:       _TestService_StreamEcho_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "egrpc/test_service.proto",
}

const (
	RichService_Process_FullMethodName = "/testpkg.RichService/Process"
)

// RichServiceClient is the client API for RichService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RichService exercises additional proto field types for schema generation
// coverage: nested messages, repeated fields, maps, and various scalar types.
type RichServiceClient interface {
	// Process accepts a RichRequest and returns a RichResponse.
	Process(ctx context.Context, in *RichRequest, opts ...grpc.CallOption) (*RichResponse, error)
}

type richServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRichServiceClient(cc grpc.ClientConnInterface) RichServiceClient {
	return &richServiceClient{cc}
}

func (c *richServiceClient) Process(ctx context.Context, in *RichRequest, opts ...grpc.CallOption) (*RichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RichResponse)
	err := c.cc.Invoke(ctx, RichService_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RichServiceServer is the server API for RichService service.
// All implementations must embed UnimplementedRichServiceServer
// for forward compatibility.
//
// RichService exercises additional proto field types for schema generation
// coverage: nested messages, repeated fields, maps, and various scalar types.
type RichServiceServer interface {
	// Process accepts a RichRequest and returns a RichResponse.
	Process(context.Context, *RichRequest) (*RichResponse, error)
	mustEmbedUnimplementedRichServiceServer()
}

// UnimplementedRichServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRichServiceServer struct{}

func (UnimplementedRichServiceServer) Process(context.Context, *RichRequest) (*RichResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedRichServiceServer) mustEmbedUnimplementedRichServiceServer() {}
func (UnimplementedRichServiceServer) testEmbeddedByValue()                     {}

// UnsafeRichServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RichServiceServer will
// result in compilation errors.
type UnsafeRichServiceServer interface {
	mustEmbedUnimplementedRichServiceServer()
}

func RegisterRichServiceServer(s grpc.ServiceRegistrar, srv RichServiceServer) {
	// If the following call panics, it indicates UnimplementedRichServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RichService_ServiceDesc, srv)
}

func _RichService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RichServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RichService_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RichServiceServer).Process(ctx, req.(*RichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RichService_ServiceDesc is the grpc.ServiceDesc for RichService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RichService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testpkg.RichService",
	HandlerType: (*RichServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _RichService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egrpc/test_service.proto",
}

const (
	SelfRefService_Traverse_FullMethodName = "/testpkg.SelfRefService/Traverse"
)

// SelfRefServiceClient is the client API for SelfRefService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SelfRefService exercises self-referencing message types for cycle detection.
type SelfRefServiceClient interface {
	// Traverse accepts a tree node.
	Traverse(ctx context.Context, in *TreeNode, opts ...grpc.CallOption) (*TreeNode, error)
}

type selfRefServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSelfRefServiceClient(cc grpc.ClientConnInterface) SelfRefServiceClient {
	return &selfRefServiceClient{cc}
}

func (c *selfRefServiceClient) Traverse(ctx context.Context, in *TreeNode, opts ...grpc.CallOption) (*TreeNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TreeNode)
	err := c.cc.Invoke(ctx, SelfRefService_Traverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelfRefServiceServer is the server API for SelfRefService service.
// All implementations must embed UnimplementedSelfRefServiceServer
// for forward compatibility.
//
// SelfRefService exercises self-referencing message types for cycle detection.
type SelfRefServiceServer interface {
	// Traverse accepts a tree node.
	Traverse(context.Context, *TreeNode) (*TreeNode, error)
	mustEmbedUnimplementedSelfRefServiceServer()
}

// UnimplementedSelfRefServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSelfRefServiceServer struct{}

func (UnimplementedSelfRefServiceServer) Traverse(context.Context, *TreeNode) (*TreeNode, error) {
	return nil, status.Error(codes.Unimplemented, "method Traverse not implemented")
}
func (UnimplementedSelfRefServiceServer) mustEmbedUnimplementedSelfRefServiceServer() {}
func (UnimplementedSelfRefServiceServer) testEmbeddedByValue()                        {}

// UnsafeSelfRefServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SelfRefServiceServer will
// result in compilation errors.
type UnsafeSelfRefServiceServer interface {
	mustEmbedUnimplementedSelfRefServiceServer()
}

func RegisterSelfRefServiceServer(s grpc.ServiceRegistrar, srv SelfRefServiceServer) {
	// If the following call panics, it indicates UnimplementedSelfRefServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SelfRefService_ServiceDesc, srv)
}

func _SelfRefService_Traverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfRefServiceServer).Traverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SelfRefService_Traverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfRefServiceServer).Traverse(ctx, req.(*TreeNode))
	}
	return interceptor(ctx, in, info, handler)
}

// SelfRefService_ServiceDesc is the grpc.ServiceDesc for SelfRefService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SelfRefService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "testpkg.SelfRefService",
	HandlerType: (*SelfRefServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Traverse",
			Handler:    _SelfRefService_Traverse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egrpc/test_service.proto",
}
